dofile(vim.fn.stdpath('config') .. '/custom/system.lua')
dofile(vim.fn.stdpath('config') .. '/custom/display.lua')
dofile(vim.fn.stdpath('config') .. '/custom/keybinds.lua')
dofile(vim.fn.stdpath('config') .. '/custom/filetype.lua')
dofile(vim.fn.stdpath('config') .. '/custom/fold.lua')
dofile(vim.fn.stdpath('config') .. '/custom/functions.lua')
